# Get all players
GET http://localhost:3000/player
Accept: application/json

###

# Get a single player by ID
GET http://localhost:3000/player/691c9a7808188f140590d5bf
Accept: application/json

###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Chancell",
    "lastName": "Mbemba",
    "countryName": "DRC",
    "clubName": "Marseille",
    "age": 38,
    "position": "Defense",
    "goals": 482
  }

###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Samuel",
    "lastName": "Eto'o",
    "countryName": "Cameroon",
    "clubName": "Asemillam",
    "age": 46,
    "position": "Attack",
    "goals": 655
  }
###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Lionel",
    "lastName": "Messi",
    "countryName": "Argentina",
    "clubName": "Paris Saint germain",
    "age": 46,
    "position": "Attack",
    "goals": 999
  }
###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Christiano",
    "lastName": "Ronaldo",
    "countryName": "Portigal",
    "clubName": "Aser",
    "age": 33,
    "position": "Attack",
    "goals": 989
  }
###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Tresor",
    "lastName": "Mputu",
    "countryName": "DRC",
    "clubName": "Mazembe",
    "age": 41,
    "position": "Attack",
    "goals": 477
  }
###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Samuel",
    "lastName": "Kamatuka",
    "countryName": "Namibia",
    "clubName": "Ma melody",
    "age": 31,
    "position": "Attack",
    "goals": 211
  }
###

# Create a new player
POST http://localhost:3000/player
Content-Type: application/json

 {
    "firstName": "Theo",
    "lastName": "Bongonda",
    "countryName": "Drc",
    "clubName": "Chelsea",
    "age": 29,
    "position": "Attack",
    "goals": 344
  }
###

# Update a player by ID (partial update)
PUT http://localhost:3000/player/691c9aa308188f140590d5c0
Content-Type: application/json

{
  "firstName": "Smart",
  "clubName": "Real Madrid"
}

###

# Delete a player by ID
DELETE http://localhost:3000/player/691c9aca08188f140590d5c1
Accept: application/json