# Get all students
GET http://localhost:3000/student
Accept: application/json

###

# Get a single student by ID
GET http://localhost:3000/student/67db3424290fc590c9b06c63
Accept: application/json

###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Timothy",
    "lastName": "Timothy",
    "age": 31,
    "favoriteSubject": "Agriculture",
    "grade": "B+",
    "email": "timo@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Zakuani",
    "lastName": "Malenga",
    "age": 31,
    "favoriteSubject": "Biology",
    "grade": "B+",
    "email": "zak@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Rejoyce",
    "lastName": "Mwenyemali",
    "age": 31,
    "favoriteSubject": "Math",
    "grade": "c+",
    "email": "rej@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Moriah",
    "lastName": "Mwinkeu",
    "age": 23,
    "favoriteSubject": "History",
    "grade": "A+",
    "email": "moriah@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Rebecca",
    "lastName": "Shianga",
    "age": 24,
    "favoriteSubject": "History",
    "grade": "B",
    "email": "rebecca@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Rachel",
    "lastName": "Shilongo",
    "age": 31,
    "favoriteSubject": "Technology",
    "grade": "A",
    "email": "shilongo@example.com"
}
###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Ferdinard",
    "lastName": "Kambere",
    "age": 31,
    "favoriteSubject": "Accounting",
    "grade": "c+",
    "email": "fer@example.com"
}
###

# Update a student by ID (partial update)
PUT http://localhost:3000/student/67db39cd3ceef80d58143435
Content-Type: application/json

{
  "lastName": "Island",
  "age": 27
}

###

# Delete a student by ID
DELETE http://localhost:3000/student/67db482da595bbf1e685a7c9
Accept: application/json